import { DiseaseCategory } from "./DoctorSection";

export const diseaseListIntial:DiseaseCategory[] = [
    {name:"Urgent Care (Sick Visit)", 
    iconPath:"/vector.svg",
    diseases: [
      "Acute Bronchitis",
      "Ear Allergies",
      "COVID-19 Rx (Paxlovid)",
      "Dental infection",
      "Ear infection",
      "flu (Influenza)",
      "Migraine relief",
      "Motion Sicknesa",
      "Nausea/Vomiting",
      "Cold Sore",
      "Pain Relief",
      "Pediatric",
      "Phone Consult",
      "Pink Eye",
      "Sinus Infection",
      "Strep Throat",
      "Stye",
      "Thrush (Oral)",
      "Respiratory Infection",
      "UTI"],
      isSelected:true
    },
    {name:"Sexually Transmitted Diseases",
    iconPath:"/group-411.svg",
    diseases: [
    "Chlamydia",
    "Herpes",
    "Trich,Chlamydia,Gonorrhea",
    "Urethritis",
    "Chlamydia & Gonorrhea",
    "HIV Exposure (PEP)",
    "Trichomoniasis",
    "Ureaplasma",
    "Genital Wart",
    "HIV prevention (PEP)",
    "Unsure?",
    "Mycoplasma",
    "Gonorrhea"]
    },
    {name:"Women's Health",
    iconPath:"/group-232.svg",
    diseases: [
    "Acne(Women)",
    "Anti-aging(Women)",
    "Bacterial Vaginosis",
    "Birth Control",
    "Dermatology(Women)",
    "Excessive Sweating(Wom,en)",
    "Menstrual Suppression",
    "Pediatrics",
    "Sexual Disorder",
    "Urinary Incontinence",
    "UTI(Women)",
    "Vaginal Yeast Infection",
    "Weight loss Rx(Women)",
    "Women's Hair Loss",
    ]
    },
    {name:"Men's Health",
    iconPath:"/group-233.svg",
    diseases:[
    "Balanitis",
    "Erectile Dysfunction",
    "Excessive Sweating(men)",
    "Genitial Warts",
    "Jock Itch",
    "Men's Hair Loss",
    "Premature Ejactulation",
    "UTI(Men)",
    "Weight Loss Rx(men)",]
    },
    {name:"Psychiatry",
    iconPath:"/group-421.svg",
    diseases: [
    "ADHD",
    "Depression",
    "General Anxiety",
    "Panic Disorder",
    "Social Anxiety",]
    },
    {name:"Chronic Medical Conditions",
    iconPath:"/group-401.svg",
    diseases:[
    "Asthma",
    "Chronic Allergies",
    "Gerd(Acid Reflux)",
    "Gout",
    "High Cholestrol",
    "Hypertension Treatments",
    "Hypothyroidism",
    "Insomnia",
    "Migraine",
    "Prescription Refill",
    "Smoking Cessation",
    "Weight Loss Rx(Obesity)"],
  },
  {
    name:"Dermatology",
    iconPath:"/group-181.svg",
    diseases:[
    "Abscess(Boil)",
    "Acne",
    "Anti-Aging",
    "Athlete's Foot",
    "Cellulitis",
    "Dandruff",
    "Dermmatology",
    "Eczema",
    "Excessive Sweating ",
    "Facial Wrinkles",
    "Hair Loss(Men)",
    "Hair Loss(Women)",
    "Lice",
    "Poison Ivy",
    "Psoriasis",
    "Rosacea",
    "Scables",
    "Shingles",
    "Skin Infection",
    "Skin,Nail, and Hair"],
    },
    {name:"Miscellaneous Health", 
    iconPath:"/group-391.svg",
    diseases:[
    "Can't Find Your Condition?",
    "Clearence/Return to work Letter",
    "Lab result Review",
    "Medical Excuse Note",
    "Rx Refill",
    "Lab testing",
    "Imaging",]
    },
    {
      name:"Online prescription refill", 
      iconPath:"/group-31.svg",
      diseases:[]
    }
  ]
